"""esquema inicial

Revision ID: 0001
Revises:
Create Date: 2026-09-26 16:15:26.967877
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.security import DOWNGRADE_SQL, POST_DOWNGRADE_SQL, PRE_TABLES, post_tables_sql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(PRE_TABLES)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("user_email", sa.String(length=320), nullable=True),
        sa.Column("acao", sa.String(length=60), nullable=False),
        sa.Column("entidade", sa.String(length=60), nullable=True),
        sa.Column("entidade_id", sa.String(length=80), nullable=True),
        sa.Column("detalhes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("hash_anterior", sa.String(length=64), nullable=True),
        sa.Column("hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_acao"), "audit_log", ["acao"], unique=False)
    op.create_index(op.f("ix_audit_log_org_id"), "audit_log", ["org_id"], unique=False)
    op.create_table(
        "condition_attributes",
        sa.Column("chave", sa.String(length=60), nullable=False),
        sa.Column("fonte", sa.String(length=20), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("pergunta", sa.Text(), nullable=False),
        sa.Column("valores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("chave", name=op.f("pk_condition_attributes")),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=False),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "ref_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("versoes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("regras_aprovadas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("regras_pendentes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("completude", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ref_snapshots")),
        sa.UniqueConstraint("hash", name=op.f("uq_ref_snapshots_hash")),
    )
    op.create_table(
        "ref_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fonte", sa.String(length=20), nullable=False),
        sa.Column("rotulo", sa.String(length=200), nullable=False),
        sa.Column("url_origem", sa.Text(), nullable=True),
        sa.Column("modo_coleta", sa.String(length=20), nullable=False),
        sa.Column("coletado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("arquivo_path", sa.Text(), nullable=False),
        sa.Column("arquivo_nome", sa.String(length=300), nullable=True),
        sa.Column("vigencia_inicio", sa.Date(), nullable=True),
        sa.Column("vigencia_fim", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("importado_por", sa.UUID(), nullable=True),
        sa.Column("importado_por_email", sa.String(length=320), nullable=True),
        sa.Column("estatisticas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("avisos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("erro", sa.Text(), nullable=True),
        sa.Column("embeddings_status", sa.String(length=20), nullable=False),
        sa.Column("embeddings_modelo", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ref_versions")),
        sa.UniqueConstraint("fonte", "sha256", name="uq_ref_versions_fonte_sha"),
    )
    op.create_index(op.f("ix_ref_versions_fonte"), "ref_versions", ["fonte"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_platform_admin", sa.Boolean(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("ultimo_login_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "abbreviations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("abreviacao", sa.String(length=40), nullable=False),
        sa.Column("expansao", sa.String(length=120), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_abbreviations_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_abbreviations")),
        sa.UniqueConstraint("org_id", "abreviacao", name="uq_abbreviations_org_abrev"),
    )
    op.create_table(
        "cclasstrib_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("codigo", sa.String(length=6), nullable=False),
        sa.Column("cst", sa.String(length=3), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("nome_reduzido", sa.Text(), nullable=True),
        sa.Column("perc_red_ibs", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("perc_red_cbs", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("tipo_aliquota", sa.String(length=40), nullable=True),
        sa.Column("nro_anexo", sa.Integer(), nullable=True),
        sa.Column("url_legislacao", sa.Text(), nullable=True),
        sa.Column("texto_regulamento_cbs", sa.Text(), nullable=True),
        sa.Column("texto_regulamento_ibs", sa.Text(), nullable=True),
        sa.Column("ind_nfe", sa.Boolean(), nullable=False),
        sa.Column("ind_nfce", sa.Boolean(), nullable=False),
        sa.Column("ind_nfse", sa.Boolean(), nullable=False),
        sa.Column("indicadores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_inicio", sa.Date(), nullable=True),
        sa.Column("data_fim", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["ref_versions.id"],
            name=op.f("fk_cclasstrib_codes_version_id_ref_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cclasstrib_codes")),
        sa.UniqueConstraint("version_id", "codigo", name="uq_cclasstrib_version_codigo"),
    )
    op.create_table(
        "cclasstrib_correlacoes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("cclasstrib", sa.String(length=6), nullable=False),
        sa.Column("nro_anexo", sa.Integer(), nullable=True),
        sa.Column("descricao_anexo", sa.Text(), nullable=True),
        sa.Column("codigo_ncm_nbs", sa.String(length=12), nullable=False),
        sa.Column("tipo_codigo", sa.String(length=3), nullable=False),
        sa.Column("tipo_permissao", sa.String(length=20), nullable=True),
        sa.Column("descricao_condicao", sa.Text(), nullable=True),
        sa.Column("descricao_excecao", sa.Text(), nullable=True),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column("nro_item_anexo", sa.String(length=20), nullable=True),
        sa.Column("descricao_item_anexo", sa.Text(), nullable=True),
        sa.Column("data_inicio", sa.Date(), nullable=True),
        sa.Column("data_fim", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["ref_versions.id"],
            name=op.f("fk_cclasstrib_correlacoes_version_id_ref_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cclasstrib_correlacoes")),
    )
    op.create_index(
        "ix_correl_version_codigo", "cclasstrib_correlacoes", ["version_id", "codigo_ncm_nbs"], unique=False
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("razao_social", sa.String(length=250), nullable=False),
        sa.Column("nome_fantasia", sa.String(length=250), nullable=True),
        sa.Column("cnpj", sa.String(length=14), nullable=False),
        sa.Column("regime_tributario", sa.String(length=30), nullable=False),
        sa.Column("uf", sa.String(length=2), nullable=False),
        sa.Column("atividade_principal", sa.String(length=300), nullable=True),
        sa.Column("cnae", sa.String(length=10), nullable=True),
        sa.Column("atributos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_companies_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("org_id", "cnpj", name="uq_companies_org_cnpj"),
    )
    op.create_index(op.f("ix_companies_org_id"), "companies", ["org_id"], unique=False)
    op.create_table(
        "cst_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("cst", sa.String(length=3), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("indicadores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_inicio", sa.Date(), nullable=True),
        sa.Column("data_fim", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["version_id"], ["ref_versions.id"], name=op.f("fk_cst_codes_version_id_ref_versions"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cst_codes")),
        sa.UniqueConstraint("version_id", "cst", name="uq_cst_codes_version_cst"),
    )
    op.create_table(
        "export_layouts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("colunas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("separador_csv", sa.String(length=3), nullable=False),
        sa.Column("ncm_formatado", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_export_layouts_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_layouts")),
    )
    op.create_index(op.f("ix_export_layouts_org_id"), "export_layouts", ["org_id"], unique=False)
    op.create_table(
        "legal_provisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("anexo", sa.String(length=10), nullable=True),
        sa.Column("titulo_anexo", sa.Text(), nullable=True),
        sa.Column("item", sa.String(length=20), nullable=True),
        sa.Column("artigo", sa.String(length=20), nullable=True),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("codigos_citados", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["ref_versions.id"],
            name=op.f("fk_legal_provisions_version_id_ref_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_provisions")),
    )
    op.create_index("ix_legal_provisions_anexo_item", "legal_provisions", ["version_id", "anexo", "item"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("papel", sa.String(length=20), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_memberships_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("org_id", "user_id", name="uq_memberships_org_user"),
    )
    op.create_index(op.f("ix_memberships_org_id"), "memberships", ["org_id"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "nbs_nodes",
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(length=12), nullable=False),
        sa.Column("codigo_formatado", sa.String(length=20), nullable=False),
        sa.Column("nivel", sa.String(length=20), nullable=False),
        sa.Column("codigo_pai", sa.String(length=12), nullable=True),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("descricao_completa", sa.Text(), nullable=False),
        sa.Column("folha", sa.Boolean(), nullable=False),
        sa.Column("data_inicio", sa.Date(), nullable=True),
        sa.Column("data_fim", sa.Date(), nullable=True),
        sa.Column("ato_legal", sa.String(length=200), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('portuguese', immutable_unaccent(descricao_completa))", persisted=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["version_id"], ["ref_versions.id"], name=op.f("fk_nbs_nodes_version_id_ref_versions"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nbs_nodes")),
        sa.UniqueConstraint("version_id", "codigo", name="uq_nbs_nodes_version_codigo"),
    )
    op.create_index("ix_nbs_nodes_codigo", "nbs_nodes", ["codigo"], unique=False)
    op.create_index("ix_nbs_nodes_tsv", "nbs_nodes", ["tsv"], unique=False, postgresql_using="gin")
    op.create_table(
        "ncm_nodes",
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(length=12), nullable=False),
        sa.Column("codigo_formatado", sa.String(length=20), nullable=False),
        sa.Column("nivel", sa.String(length=20), nullable=False),
        sa.Column("codigo_pai", sa.String(length=12), nullable=True),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("descricao_completa", sa.Text(), nullable=False),
        sa.Column("folha", sa.Boolean(), nullable=False),
        sa.Column("data_inicio", sa.Date(), nullable=True),
        sa.Column("data_fim", sa.Date(), nullable=True),
        sa.Column("ato_legal", sa.String(length=200), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('portuguese', immutable_unaccent(descricao_completa))", persisted=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["version_id"], ["ref_versions.id"], name=op.f("fk_ncm_nodes_version_id_ref_versions"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ncm_nodes")),
        sa.UniqueConstraint("version_id", "codigo", name="uq_ncm_nodes_version_codigo"),
    )
    op.create_index("ix_ncm_nodes_codigo", "ncm_nodes", ["codigo"], unique=False)
    op.create_index("ix_ncm_nodes_tsv", "ncm_nodes", ["tsv"], unique=False, postgresql_using="gin")
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("titulo", sa.String(length=200), nullable=False),
        sa.Column("mensagem", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=300), nullable=True),
        sa.Column("lida_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_notifications_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_org_id"), "notifications", ["org_id"], unique=False)
    op.create_table(
        "org_settings",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("limiar_confirmado", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("limiar_corrigido", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("limiar_escalonamento", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("modelo_principal", sa.String(length=80), nullable=True),
        sa.Column("modelo_escalonamento", sa.String(length=80), nullable=True),
        sa.Column("modelo_leve", sa.String(length=80), nullable=True),
        sa.Column("usar_modelo_leve", sa.Boolean(), nullable=False),
        sa.Column("orcamento_mensal_usd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("alerta_orcamento_pct", sa.Integer(), nullable=False),
        sa.Column("lote_min_itens", sa.Integer(), nullable=True),
        sa.Column("imposto_seletivo_exige_analise", sa.Boolean(), nullable=False),
        sa.Column("retencao_arquivos_dias", sa.Integer(), nullable=False),
        sa.Column("ultimo_alerta_orcamento", sa.String(length=7), nullable=True),
        sa.Column("extras", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_org_settings_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("org_id", name=op.f("pk_org_settings")),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("familia_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("expira_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revogado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("substituido_por", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_familia_id"), "refresh_tokens", ["familia_id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "approved_memory",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("gtin", sa.String(length=20), nullable=True),
        sa.Column("descricao_normalizada", sa.Text(), nullable=False),
        sa.Column("descricao_hash", sa.String(length=64), nullable=False),
        sa.Column("tipo_codigo", sa.String(length=3), nullable=False),
        sa.Column("codigo", sa.String(length=12), nullable=False),
        sa.Column("cst", sa.String(length=3), nullable=True),
        sa.Column("cclasstrib", sa.String(length=6), nullable=True),
        sa.Column("atributos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=True),
        sa.Column("audit_id", sa.UUID(), nullable=True),
        sa.Column("snapshot_id", sa.UUID(), nullable=True),
        sa.Column("aprovado_por", sa.UUID(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_approved_memory_company_id_companies"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_approved_memory_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approved_memory")),
    )
    op.create_index(op.f("ix_approved_memory_org_id"), "approved_memory", ["org_id"], unique=False)
    op.create_index("ix_memory_company_desc", "approved_memory", ["company_id", "descricao_hash"], unique=False)
    op.create_index("ix_memory_company_gtin", "approved_memory", ["company_id", "gtin"], unique=False)
    op.create_table(
        "company_access",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("membership_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_company_access_company_id_companies"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
            name=op.f("fk_company_access_membership_id_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_company_access_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_access")),
        sa.UniqueConstraint("membership_id", "company_id", name="uq_company_access"),
    )
    op.create_index(op.f("ix_company_access_org_id"), "company_access", ["org_id"], unique=False)
    op.create_table(
        "legal_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("anexo", sa.String(length=10), nullable=True),
        sa.Column("item", sa.String(length=20), nullable=True),
        sa.Column("titulo_anexo", sa.Text(), nullable=True),
        sa.Column("descricao_legal", sa.Text(), nullable=False),
        sa.Column("dispositivo_legal", sa.Text(), nullable=False),
        sa.Column("tipo_tratamento", sa.String(length=30), nullable=False),
        sa.Column("tipo_codigo", sa.String(length=3), nullable=True),
        sa.Column("abrangencia", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("excecoes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("condicoes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cst_ibs_cbs", sa.String(length=3), nullable=True),
        sa.Column("cclasstrib", sa.String(length=6), nullable=True),
        sa.Column("vigencia_inicio", sa.Date(), nullable=True),
        sa.Column("vigencia_fim", sa.Date(), nullable=True),
        sa.Column("prioridade", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("origem", sa.String(length=30), nullable=False),
        sa.Column("fonte_version_id", sa.UUID(), nullable=True),
        sa.Column("provision_id", sa.UUID(), nullable=True),
        sa.Column("controverso", sa.Boolean(), nullable=False),
        sa.Column("nota_controversia", sa.Text(), nullable=True),
        sa.Column("erros_validacao", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("avisos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extracao", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revisado_por", sa.UUID(), nullable=True),
        sa.Column("revisado_por_email", sa.String(length=320), nullable=True),
        sa.Column("revisado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nota_revisao", sa.Text(), nullable=True),
        sa.Column("substitui_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["fonte_version_id"], ["ref_versions.id"], name=op.f("fk_legal_rules_fonte_version_id_ref_versions")
        ),
        sa.ForeignKeyConstraint(
            ["provision_id"], ["legal_provisions.id"], name=op.f("fk_legal_rules_provision_id_legal_provisions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_rules")),
        sa.UniqueConstraint("slug", "versao", name="uq_legal_rules_slug_versao"),
    )
    op.create_index("ix_legal_rules_status", "legal_rules", ["status"], unique=False)
    op.create_table(
        "mapping_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("sistema_origem", sa.String(length=120), nullable=True),
        sa.Column("mapeamento", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assinatura_colunas", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_mapping_templates_company_id_companies"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_mapping_templates_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mapping_templates")),
    )
    op.create_index(op.f("ix_mapping_templates_org_id"), "mapping_templates", ["org_id"], unique=False)
    op.create_table(
        "uploaded_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("nome_original", sa.String(length=300), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("tamanho_bytes", sa.BigInteger(), nullable=False),
        sa.Column("formato", sa.String(length=10), nullable=False),
        sa.Column("encoding", sa.String(length=20), nullable=True),
        sa.Column("separador", sa.String(length=3), nullable=True),
        sa.Column("planilha", sa.String(length=120), nullable=True),
        sa.Column("planilhas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("linha_cabecalho", sa.Integer(), nullable=False),
        sa.Column("total_linhas", sa.Integer(), nullable=False),
        sa.Column("colunas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("amostra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enviado_por", sa.UUID(), nullable=True),
        sa.Column("expurgar_em", sa.Date(), nullable=True),
        sa.Column("expurgado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_uploaded_files_company_id_companies"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_uploaded_files_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploaded_files")),
    )
    op.create_index(op.f("ix_uploaded_files_org_id"), "uploaded_files", ["org_id"], unique=False)
    op.create_table(
        "audits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("nome", sa.String(length=200), nullable=False),
        sa.Column("mapeamento", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("modo", sa.String(length=20), nullable=True),
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("contexto_operacao", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_itens", sa.Integer(), nullable=False),
        sa.Column("contadores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("problemas_resumo", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("estimativa", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("custo_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("tokens", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("configuracao", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("erro", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("iniciado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("concluido_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_audits_company_id_companies"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["uploaded_files.id"], name=op.f("fk_audits_file_id_uploaded_files"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_audits_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["ref_snapshots.id"], name=op.f("fk_audits_snapshot_id_ref_snapshots")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audits")),
    )
    op.create_index(op.f("ix_audits_company_id"), "audits", ["company_id"], unique=False)
    op.create_index(op.f("ix_audits_org_id"), "audits", ["org_id"], unique=False)
    op.create_index(op.f("ix_audits_status"), "audits", ["status"], unique=False)
    op.create_table(
        "legal_rule_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("tipo_codigo", sa.String(length=3), nullable=False),
        sa.Column("prefixo", sa.String(length=12), nullable=False),
        sa.Column("excecao", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["legal_rules.id"], name=op.f("fk_legal_rule_codes_rule_id_legal_rules"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_rule_codes")),
    )
    op.create_index(op.f("ix_legal_rule_codes_rule_id"), "legal_rule_codes", ["rule_id"], unique=False)
    op.create_index("ix_rule_codes_prefixo", "legal_rule_codes", ["tipo_codigo", "prefixo"], unique=False)
    op.create_table(
        "audit_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("linha", sa.Integer(), nullable=False),
        sa.Column("codigo_interno", sa.String(length=80), nullable=False),
        sa.Column("codigo_interno_gerado", sa.Boolean(), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("ncm_informado", sa.String(length=40), nullable=True),
        sa.Column("nbs_informado", sa.String(length=40), nullable=True),
        sa.Column("tipo_informado", sa.String(length=40), nullable=True),
        sa.Column("gtin", sa.String(length=20), nullable=True),
        sa.Column("cest", sa.String(length=20), nullable=True),
        sa.Column("unidade", sa.String(length=20), nullable=True),
        sa.Column("marca", sa.String(length=120), nullable=True),
        sa.Column("categoria", sa.String(length=200), nullable=True),
        sa.Column("cst_atual", sa.String(length=10), nullable=True),
        sa.Column("cclasstrib_atual", sa.String(length=10), nullable=True),
        sa.Column("ncm", sa.String(length=12), nullable=True),
        sa.Column("nbs", sa.String(length=12), nullable=True),
        sa.Column("problemas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duplicado_de", sa.Integer(), nullable=True),
        sa.Column("ignorado", sa.Boolean(), nullable=False),
        sa.Column("descricao_normalizada", sa.Text(), nullable=True),
        sa.Column("tipo", sa.String(length=20), nullable=True),
        sa.Column("etapa", sa.String(length=40), nullable=True),
        sa.Column("tentativa", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("motivos", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("perguntas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("origem", sa.String(length=30), nullable=True),
        sa.Column("memory_id", sa.UUID(), nullable=True),
        sa.Column("tipo_codigo_sugerido", sa.String(length=3), nullable=True),
        sa.Column("codigo_sugerido", sa.String(length=12), nullable=True),
        sa.Column("cst_sugerido", sa.String(length=3), nullable=True),
        sa.Column("cclasstrib_sugerido", sa.String(length=6), nullable=True),
        sa.Column("regra_id", sa.UUID(), nullable=True),
        sa.Column("regras_consideradas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tipo_tratamento", sa.String(length=30), nullable=True),
        sa.Column("dispositivo_legal", sa.Text(), nullable=True),
        sa.Column("imposto_seletivo", sa.Boolean(), nullable=False),
        sa.Column("confianca", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("confianca_componentes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("atributos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("julgamento", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("escalonamento", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("estrutura", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("custo_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("processado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("erro", sa.Text(), nullable=True),
        sa.Column("revisao_status", sa.String(length=20), nullable=False),
        sa.Column("final_tipo_codigo", sa.String(length=3), nullable=True),
        sa.Column("final_codigo", sa.String(length=12), nullable=True),
        sa.Column("final_cst", sa.String(length=3), nullable=True),
        sa.Column("final_cclasstrib", sa.String(length=6), nullable=True),
        sa.Column("final_regra_id", sa.UUID(), nullable=True),
        sa.Column("final_dispositivo", sa.Text(), nullable=True),
        sa.Column("revisado_por", sa.UUID(), nullable=True),
        sa.Column("revisado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["audits.id"], name=op.f("fk_audit_items_audit_id_audits"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_audit_items_company_id_companies"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_audit_items_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_items")),
    )
    op.create_index("ix_audit_items_audit_linha", "audit_items", ["audit_id", "linha"], unique=False)
    op.create_index("ix_audit_items_audit_revisao", "audit_items", ["audit_id", "revisao_status"], unique=False)
    op.create_index("ix_audit_items_audit_status", "audit_items", ["audit_id", "status"], unique=False)
    op.create_index(op.f("ix_audit_items_org_id"), "audit_items", ["org_id"], unique=False)
    op.create_table(
        "export_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("formato", sa.String(length=10), nullable=False),
        sa.Column("layout_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("arquivo_path", sa.Text(), nullable=True),
        sa.Column("arquivo_nome", sa.String(length=200), nullable=True),
        sa.Column("total_itens", sa.Integer(), nullable=False),
        sa.Column("erro", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("concluido_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["audits.id"], name=op.f("fk_export_jobs_audit_id_audits"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_export_jobs_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_jobs")),
    )
    op.create_index(op.f("ix_export_jobs_audit_id"), "export_jobs", ["audit_id"], unique=False)
    op.create_index(op.f("ix_export_jobs_org_id"), "export_jobs", ["org_id"], unique=False)
    op.create_table(
        "llm_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("anthropic_batch_id", sa.String(length=100), nullable=True),
        sa.Column("modelo", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_requisicoes", sa.Integer(), nullable=False),
        sa.Column("contagens", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("erro", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("concluido_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["audits.id"], name=op.f("fk_llm_batches_audit_id_audits"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_llm_batches_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_batches")),
        sa.UniqueConstraint("anthropic_batch_id", name=op.f("uq_llm_batches_anthropic_batch_id")),
    )
    op.create_index(op.f("ix_llm_batches_audit_id"), "llm_batches", ["audit_id"], unique=False)
    op.create_index(op.f("ix_llm_batches_org_id"), "llm_batches", ["org_id"], unique=False)
    op.create_table(
        "item_candidates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("tipo_codigo", sa.String(length=3), nullable=False),
        sa.Column("codigo", sa.String(length=12), nullable=False),
        sa.Column("descricao_completa", sa.Text(), nullable=False),
        sa.Column("posicao", sa.Integer(), nullable=False),
        sa.Column("rank_semantico", sa.Integer(), nullable=True),
        sa.Column("rank_textual", sa.Integer(), nullable=True),
        sa.Column("score", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("codigo_atual", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["audit_items.id"], name=op.f("fk_item_candidates_item_id_audit_items"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_item_candidates_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_candidates")),
    )
    op.create_index(op.f("ix_item_candidates_item_id"), "item_candidates", ["item_id"], unique=False)
    op.create_index(op.f("ix_item_candidates_org_id"), "item_candidates", ["org_id"], unique=False)
    op.create_table(
        "item_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("acao", sa.String(length=20), nullable=False),
        sa.Column("antes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("depois", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("comentario", sa.Text(), nullable=True),
        sa.Column("lote_id", sa.UUID(), nullable=True),
        sa.Column("desfaz_review_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("user_email", sa.String(length=320), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["audits.id"], name=op.f("fk_item_reviews_audit_id_audits"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["audit_items.id"], name=op.f("fk_item_reviews_item_id_audit_items"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_item_reviews_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_reviews")),
    )
    op.create_index(op.f("ix_item_reviews_audit_id"), "item_reviews", ["audit_id"], unique=False)
    op.create_index(op.f("ix_item_reviews_item_id"), "item_reviews", ["item_id"], unique=False)
    op.create_index(op.f("ix_item_reviews_org_id"), "item_reviews", ["org_id"], unique=False)
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("audit_id", sa.UUID(), nullable=True),
        sa.Column("item_id", sa.UUID(), nullable=True),
        sa.Column("no", sa.String(length=40), nullable=False),
        sa.Column("modelo", sa.String(length=80), nullable=False),
        sa.Column("prompt_versao", sa.String(length=60), nullable=False),
        sa.Column("modo", sa.String(length=20), nullable=False),
        sa.Column("chave_idempotencia", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("requisicao", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resposta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("stop_reason", sa.String(length=30), nullable=True),
        sa.Column("tokens_entrada", sa.Integer(), nullable=False),
        sa.Column("tokens_saida", sa.Integer(), nullable=False),
        sa.Column("tokens_cache_escrita", sa.Integer(), nullable=False),
        sa.Column("tokens_cache_leitura", sa.Integer(), nullable=False),
        sa.Column("custo_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latencia_ms", sa.Integer(), nullable=True),
        sa.Column("tentativas", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=80), nullable=True),
        sa.Column("erro", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("concluido_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["audits.id"], name=op.f("fk_llm_calls_audit_id_audits"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["llm_batches.id"], name=op.f("fk_llm_calls_batch_id_llm_batches")),
        sa.ForeignKeyConstraint(
            ["item_id"], ["audit_items.id"], name=op.f("fk_llm_calls_item_id_audit_items"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_llm_calls_org_id_organizations"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
        sa.UniqueConstraint("chave_idempotencia", name=op.f("uq_llm_calls_chave_idempotencia")),
    )
    op.create_index(op.f("ix_llm_calls_audit_id"), "llm_calls", ["audit_id"], unique=False)
    op.create_index(op.f("ix_llm_calls_batch_id"), "llm_calls", ["batch_id"], unique=False)
    op.create_index(op.f("ix_llm_calls_item_id"), "llm_calls", ["item_id"], unique=False)
    op.create_index("ix_llm_calls_org_created", "llm_calls", ["org_id", "created_at"], unique=False)
    op.create_index("ix_llm_calls_status_modelo", "llm_calls", ["status", "modelo"], unique=False)
    # ### end Alembic commands ###
    op.execute(post_tables_sql())


def downgrade() -> None:
    op.execute(DOWNGRADE_SQL)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_llm_calls_status_modelo", table_name="llm_calls")
    op.drop_index("ix_llm_calls_org_created", table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_item_id"), table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_batch_id"), table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_audit_id"), table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index(op.f("ix_item_reviews_org_id"), table_name="item_reviews")
    op.drop_index(op.f("ix_item_reviews_item_id"), table_name="item_reviews")
    op.drop_index(op.f("ix_item_reviews_audit_id"), table_name="item_reviews")
    op.drop_table("item_reviews")
    op.drop_index(op.f("ix_item_candidates_org_id"), table_name="item_candidates")
    op.drop_index(op.f("ix_item_candidates_item_id"), table_name="item_candidates")
    op.drop_table("item_candidates")
    op.drop_index(op.f("ix_llm_batches_org_id"), table_name="llm_batches")
    op.drop_index(op.f("ix_llm_batches_audit_id"), table_name="llm_batches")
    op.drop_table("llm_batches")
    op.drop_index(op.f("ix_export_jobs_org_id"), table_name="export_jobs")
    op.drop_index(op.f("ix_export_jobs_audit_id"), table_name="export_jobs")
    op.drop_table("export_jobs")
    op.drop_index(op.f("ix_audit_items_org_id"), table_name="audit_items")
    op.drop_index("ix_audit_items_audit_status", table_name="audit_items")
    op.drop_index("ix_audit_items_audit_revisao", table_name="audit_items")
    op.drop_index("ix_audit_items_audit_linha", table_name="audit_items")
    op.drop_table("audit_items")
    op.drop_index("ix_rule_codes_prefixo", table_name="legal_rule_codes")
    op.drop_index(op.f("ix_legal_rule_codes_rule_id"), table_name="legal_rule_codes")
    op.drop_table("legal_rule_codes")
    op.drop_index(op.f("ix_audits_status"), table_name="audits")
    op.drop_index(op.f("ix_audits_org_id"), table_name="audits")
    op.drop_index(op.f("ix_audits_company_id"), table_name="audits")
    op.drop_table("audits")
    op.drop_index(op.f("ix_uploaded_files_org_id"), table_name="uploaded_files")
    op.drop_table("uploaded_files")
    op.drop_index(op.f("ix_mapping_templates_org_id"), table_name="mapping_templates")
    op.drop_table("mapping_templates")
    op.drop_index("ix_legal_rules_status", table_name="legal_rules")
    op.drop_table("legal_rules")
    op.drop_index(op.f("ix_company_access_org_id"), table_name="company_access")
    op.drop_table("company_access")
    op.drop_index("ix_memory_company_gtin", table_name="approved_memory")
    op.drop_index("ix_memory_company_desc", table_name="approved_memory")
    op.drop_index(op.f("ix_approved_memory_org_id"), table_name="approved_memory")
    op.drop_table("approved_memory")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_familia_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("org_settings")
    op.drop_index(op.f("ix_notifications_org_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_ncm_nodes_tsv", table_name="ncm_nodes", postgresql_using="gin")
    op.drop_index("ix_ncm_nodes_codigo", table_name="ncm_nodes")
    op.drop_table("ncm_nodes")
    op.drop_index("ix_nbs_nodes_tsv", table_name="nbs_nodes", postgresql_using="gin")
    op.drop_index("ix_nbs_nodes_codigo", table_name="nbs_nodes")
    op.drop_table("nbs_nodes")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_org_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index("ix_legal_provisions_anexo_item", table_name="legal_provisions")
    op.drop_table("legal_provisions")
    op.drop_index(op.f("ix_export_layouts_org_id"), table_name="export_layouts")
    op.drop_table("export_layouts")
    op.drop_table("cst_codes")
    op.drop_index(op.f("ix_companies_org_id"), table_name="companies")
    op.drop_table("companies")
    op.drop_index("ix_correl_version_codigo", table_name="cclasstrib_correlacoes")
    op.drop_table("cclasstrib_correlacoes")
    op.drop_table("cclasstrib_codes")
    op.drop_table("abbreviations")
    op.drop_table("users")
    op.drop_index(op.f("ix_ref_versions_fonte"), table_name="ref_versions")
    op.drop_table("ref_versions")
    op.drop_table("ref_snapshots")
    op.drop_table("organizations")
    op.drop_table("condition_attributes")
    op.drop_index(op.f("ix_audit_log_org_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_acao"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
    op.execute(POST_DOWNGRADE_SQL)
